### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by DennisWarchocki** [DennisWarchocki/capstone-project#10]
As a User, I want to have a navigation bar at the top
so that, I can easily move between the sites.

![Image](https://user-images.githubusercontent.com/109968361/194853152-9acff77c-bac2-44cd-a7ef-a7d32b5a8f6c.png)

## Acceptance criteria

- [x] a Navigation is dipslayed at the top
- [x] the Navigation Buttons are linked to a site
- [x] the buttons have a hover effect
- [x] the NavBar has a prototype styling

## Tasks
1. [x] go to the Header in the Layout
2. [x] create a nav
3. [x] create a ul inside the nav with list items
4. [x] give styling with styled components
