### ISSUE TITLE
Track meals

### ISSUE THREAD

**Issue by DennisWarchocki** [DennisWarchocki/capstone-project#2]
As a user,  
I want to save what I ate today,  
so that, I have a better overview of my diet

![Image](https://user-images.githubusercontent.com/109968361/191505051-55a69298-153c-4906-88b9-3760744cf404.png)

## Acceptance criteria

- [x] The page has a form
- [x] The form has an input
- [x] The form has a button
- [x] When the form is submitted Then the meal is saved

## Tasks

1. [x] Checkout main and pull
2. [x] Create and checkout branch
3.  [x] add from component
4. [x] handle form and save results in useState
5. [x] Use form component in index page
