### ISSUE TITLE
track-calories

### ISSUE THREAD

**Issue by DennisWarchocki** [DennisWarchocki/capstone-project#4]
**As a user,**
**I want to** see how many calories I consumed today,  
**so that,** it's easy to determine if I've reached a surplus of calories or not.
![Image](https://user-images.githubusercontent.com/109968361/191971905-7e56f7c2-ff19-4dd8-8892-820b7e181c11.png)

## Acceptance criteria

- [x] ~~The page has 2 paragraphs~~
- [x] The first paragraph should sum the values from the useState (Calories from the food consumed today)
- [x] The first Paragraph should display how much calories were consumed today
- [x] ~~The second paragraph should show how many calories you want to consume today~~

## Tasks

1.   [x] create a new branch
2.  [x] add a sum functionality which sum together the calories you consumed today
3.  [x] display the calories you consumed today in a paragraph
