### ISSUE TITLE
Timer function

### ISSUE THREAD

**Issue by DennisWarchocki** [DennisWarchocki/capstone-project#7]
As a user, I want to set a Countdown while im cooking
so that, I dont forget to get my food out of the oven ect. right in time.
<img width="363" alt="Bildschirmfoto 2022-10-07 um 11 35 55" src="https://user-images.githubusercontent.com/109968361/194523471-b42b7e8e-92fe-46d1-a843-9c0b3694abf5.png">

## Acceptance criteria

- [x] the Timer has its own page under /pages
- [x] the Timer is counting down the seconds ect.
- [x] the User can set the Days, hours, Minutes and seconds of the Countdown
- [ ] when the Countdown becomes 0 a Pop up or alarm should appear 

## Tasks

1. [x] Checkout main and pull
2. [x] Create and checkout branch
3. [x] create a new timer pager called timer.js in /pages
4. [x] import useState, useEffect
5. [x] calculate the miliseconds to seconds, minutes, hours, days
6. [x] create a form and input for the User to set the Countdown
7. [x] give the Countdown a styling with styled-components

**Comment by Murci2022** [comment]
Great job!
