### ISSUE TITLE
localStorage

### ISSUE THREAD

**Issue by DennisWarchocki** [DennisWarchocki/capstone-project#8]
As a User,
I want my Session to be saved for the next time when I visit the Webpage
so that, I dont have to type everything again and start from the bottom

![Image](https://user-images.githubusercontent.com/109968361/194512631-7093e05e-c842-4a49-ac9a-9f7a6da5b239.png)

## Acceptance criteria

- [ ] the UserData are saved in localStorage
- [ ] when the Browser is closed, and opened again, the Inputs the User did are still the same
- [ ] the Data from all pages getting saved

## Tasks

1. [ ] Checkout main and pull
2. [ ] Create and checkout branch
3. [ ] import local Storage
4. [ ] handle userData and save in localStorage
5. [ ] Displays the same Session for the User he was in last time

**Comment by Murci2022** [comment]
Great job Dennis, looks good to me.
