### ISSUE TITLE
Recipe Bookmarks

### ISSUE THREAD

**Issue by DennisWarchocki** [DennisWarchocki/capstone-project#9]
As a user, 
I want to bookmark my favorite recipes
 So that I can see a list of my favorite recipes

![Image](https://user-images.githubusercontent.com/109968361/194517882-8df563fc-db30-4e1e-ad65-8635236e4e5d.png)

## Acceptance criteria

- [ ] Bookmarks have a own page
- [ ] Recipe Bookmarks are displayed in a list
- [ ] You can see the ingredients necessary for the recipe
- [ ] You can see the cooking Guide

## Tasks

1. [ ] Checkout main and pull
2. [ ] Create and checkout branch
3. [ ] Create a new Page called recipeBookmarks.js in /pages
4. [ ] Create a list for the recipes
5. [ ] diplsay the recipes as list Items with all relevant data

**Comment by Murci2022** [comment]
I just discovered some spelling mistakes if you have time-but it looks great to me
